apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  selector:
   matchLabels:
     app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: docker.io/openzipkin/zipkin
        imagePullPolicy: Always
        ports:
        - containerPort: 9411
      #   env:
      #   - name: DB_USER_NAME
      #     valueFrom:
      #       secretKeyRef:
      #         name: banking-sc
      #         key:  DB_USER_NAME
      #   - name: DB_PASSWORD
      #     valueFrom: 
      #       secretKeyRef:
      #         name: banking-sc
      #         key: DB_PASSWORD
      #   - name: DB_HOST
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: banking-cm
      #         key: DB_HOST
      #   - name: CONFIG_SERVER_URL
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: banking-cm
      #         key: CONFIG_SERVER_URL
      # imagePullSecrets:
      #   - name: gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
spec:
  selector:
    app: zipkin
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      
#docker push  asia-docker.pkg.dev/endless-ability-398915/banking-repo/tellicaller-service:0.0.1
#docker build -t asia-docker.pkg.dev/endless-ability-398915/banking-repo/tellicaller-service:0.0.1 . --platform linux/amd64
#kubectl rollout restart deployment/your-deployment-name